### ISSUE TITLE
Warning: CalendarTags::addEvent 5th argument must not be defined

### ISSUE THREAD

**Issue by fatcrobat** [hschottm/tags#28]
Getting the following error within contao 3.5.19 and latest Tags Version.

 ```

Warning: Missing argument 5 for Contao\CalendarTags::addEvent(), called in /system/modules/calendar/classes/Calendar.php on line 174 and defined in system/modules/tags/classes/CalendarTags.php on line 22
#0 system/modules/tags/classes/CalendarTags.php(22): __error(2, 'Missing argumen...', '/home/rico/Kund...', 22, Array)
#1 system/modules/calendar/classes/Calendar.php(174): Contao\CalendarTags->addEvent(Object(Contao\Model\Collection), '1483570800', '1514761199', 'http://corporat...')
#2 system/modules/calendar/classes/Calendar.php(76): Contao\Calendar->generateFiles(Array)
#3 system/modules/core/controllers/FrontendCron.php(100): Contao\Calendar->generateFeeds()
#4 system/cron/cron.php(20): Contao\FrontendCron->run()
#5 {main}
```

If a method is overwritten, the arguments must match, so please change the 5th argument from

```
 $strLink 
```

to 

```
 $strLink  = ''
```

Error occurs when accessing system/cron/cron.php directly.

Thanks

**Comment by hschottm** [comment]
Fixed in b3135cb8fa427683ca15e6ab54581e210e17f2cb
